check_ins_inactive:
  fields:
    - full_name
    - email
    - department
    - department_block
    - check_date
    - check_in_time
    - check_out_date
    - check_out_time
    - charity
    - hours_worked
  filename: "inactive_check_ins"